# domains/capabilities/schemas.py

from pydantic import BaseModel, ConfigDict, Field
from typing import List, Optional
from uuid import UUID

class LocationCapabilitiesResponse(BaseModel):
    """
    Validates the JSON output generated by the vw_capabilities_location view.
    Used by the Streamlit frontend to populate Step 2 and Step 5 of the wizard.
    """
    location_id: UUID = Field(..., description="The unique identifier for the physical location/PoP")
    deployed_hardware: List[str] = Field(default_factory=list, description="Array of Role + Model combinations deployed at this site")
    location_supported_ports: List[str] = Field(default_factory=list, description="Aggregated port speeds available across all devices at this site")
    location_supported_services: List[str] = Field(default_factory=list, description="Aggregated service types available across all devices at this site")

    model_config = ConfigDict(from_attributes=True)

# Append to domains/capabilities/schemas.py

# --- Master Reference Schemas ---

class RefServiceCreate(BaseModel):
    service_name: str = Field(..., max_length=50, description="Name of the service (e.g., E-Line EVPL)")
    layer: str = Field(..., max_length=10, description="OSI Layer (e.g., L2, L3)")

class RefServiceResponse(RefServiceCreate):
    service_id: UUID
    model_config = ConfigDict(from_attributes=True)


class RefSpeedCreate(BaseModel):
    speed_value: str = Field(..., max_length=20)
    is_fabric_port_capable: bool = False
    is_service_capable: bool = True

class RefSpeedResponse(RefSpeedCreate):
    speed_id: UUID
    model_config = ConfigDict(from_attributes=True)


# --- Hardware Profile Schemas ---

class HardwareProfileCreate(BaseModel):
    device_role: str = Field(..., max_length=50, description="e.g., VAR, ES, SDR")
    device_model: str = Field(..., max_length=100, description="e.g., MX10004, ACX7100")

class HardwareProfileResponse(HardwareProfileCreate):
    profile_id: UUID
    model_config = ConfigDict(from_attributes=True)


# --- Capability Mapping Schemas ---

class ProfileServiceAssign(BaseModel):
    service_id: UUID
    speed_id: UUID

class ProfileServiceResponse(BaseModel):
    capability_id: UUID
    profile_id: UUID
    service_id: UUID
    speed_id: UUID
    model_config = ConfigDict(from_attributes=True)